

<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <title><?php echo $titulo; ?></title>  
</head>


<body>
    <?php echo form_open('equipe/inserir', 'id="form-equipe"'); ?>
    
    <form action="" method="post" ENCTYPE="multipart/form-data">
      <div class="row">
        <div class="form-group col-md-5">
            <label for="username">Username</label> <input type="text" class="form-control" id="username" name="username"
                placeholder="informe o nome do Usuario"
                value="<?php echo isset($view_username) ? $view_username: '' ; ?>">
        </div>     
        <div class="form-group col-md-5">
            <label for="password">Senha</label> <input type="text" class="form-control" id="password" name="password"
                placeholder="informe a senha"
                value="<?php echo isset($view_password) ? $view_password: '' ; ?>">
        </div>
    </div>

        <div class="row">
            <div class="form-group col-md-5">
                 <label for="cargo">Cargo</label> <input type="text" class="form-control" id="cargo" name="cargo" placeholder="informe a senha" 
                 value="<?php echo isset($view_cargo) ? $view_cargo: '' ; ?>">
            </div>
        </div>

        <div class="row">
        <div class="col-md-12">
            <input type="submit" class="btn btn-primary" name="btsalvar" value="Salvar" /> 
                <a onClick="history.go(-1)" class="btn btn-default">Cancelar</a>
        </div>

    <?php echo form_close(); ?>
</body>
</html>