<!DOCTYPE html>
<html lang="pt-br">

<body>
	<?php echo form_open('orcamentos/atualizar', 'id="form-orcamentos"'); ?>
	
	<input type="hidden" name="ocod" value="<?php echo $dados_orcamentos[0]->ocod; ?>"/>
	<input type="hidden" name="cliente" value="<?php echo $dados_orcamentos[0]->cliente; ?>"/>
	<input type="hidden" name="produto" value="<?php echo $dados_orcamentos[0]->produto; ?>"/>
 	
 	<div class="row">
        <div class="form-group col-md-6">
			<label for="cliente">Cliente:</label><br/>
			<input type="text" class="form-control" name="clienteNome" readonly 
				value="<?php echo $dados_orcamentos[0]->cnome; ?>"/>
			<div class="error"><?php echo form_error('cliente'); ?></div>
		</div> 	
		<div class="form-group col-md-6">
			<label for="produto">Produto:</label><br/>
			<input type="text" class="form-control" name="produtoNome" readonly
				value="<?php echo $dados_orcamentos[0]->pnome; ?>"/>
			<div class="error"><?php echo form_error('produto'); ?></div>
		</div>	

	</div>

	<div class="row">
        <div class="form-group col-md-6">
			<label for="orcdate">Data:</label><br/>
			<input type="text" class="form-control" name="orcdate" value="<?php echo $dados_orcamentos[0]->orcdate; ?>"/>
			<div class="error"><?php echo form_error('orcdate'); ?></div>
		</div>

		<div class="form-group col-md-6">
		<label for="situacao">Situação:</label><br/>
	        <div class="col-md-3">
	          <input type="radio" name="situacao" value="Quente" checked> Quente<br>
	        </div>
	        <div class="col-md-2">
	          <input type="radio" name="situacao" value="Frio"> Frio<br>
	        </div>
	        <div class="col-md-3">
	          <input type="radio" name="situacao" value="Parado"> Parado<br>
	        </div>
        </div>

	</div>

	<div class="row">
            <div class="form-group col-md-6">
              <label for="valor">Valor</label> 
              <input type="text" class="form-control" id="valor" name="valor"
                placeholder="informe o valor" required
                value="<?php echo isset($view_valor) ? $view_valor : '' ; ?>">
            </div>

            <div class="form-group col-md-6">
              <label for="numero">Numero do Orçamento</label> 
              <input type="text" class="form-control" id="numero" 
                name="numero" required placeholder="informe o numero do orçamento"
                value="<?php echo isset($view_numero) ? $view_numero : '' ; ?>">
            </div>   
          </div>

          <div class="row">
            <div class="form-group col-md-6">
            <label for="autor_show">Autor</label> <input type="text" class="form-control" id="autor_show" 
            name="autor_show" readonly
            value="<?php echo $_SESSION['usuario_logado']['username']; ?> "/>
            </div>
        
            <div>
              <input type="hidden" name="autor" value="<?php echo $_SESSION['usuario_logado']['id'];  ?>"/>
            </div>
          </div>

 	<div class="row">
        <div class="col-md-12">
            <input type="submit" class="btn btn-primary" name="btsalvar" value="Salvar" /> 
                <a onClick="history.go(-1)" class="btn btn-default">Cancelar</a>
        </div>
    </div>
 
	<?php echo form_close(); ?>
</body>
</html>