

<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <title><?php echo $titulo; ?></title>  
</head>


<body>
    <?php echo form_open('produtos/inserir', 'id="form-produtos"'); ?>
    
    <form action="" method="post" ENCTYPE="multipart/form-data">
      <div class="row">
        <div class="form-group col-md-5">
            <label for="pnome">Nome do Produto</label> <input type="text" class="form-control" id="pnome" name="pnome"
                placeholder="informe o nome do Produto"
                value="<?php echo isset($view_pnome) ? $view_pnome: '' ; ?>">
        </div>     
        <div class="form-group col-md-5">
            <label for="nome">Descrição</label> <input type="text" class="form-control" id="descricao" name="descricao"
                placeholder="informe uma Descrição do produto"
                value="<?php echo isset($view_descricao) ? $view_descricao: '' ; ?>">
        </div>
    </div>
    
        <div class="row">
        <div class="col-md-12">
            <input type="submit" class="btn btn-primary" name="btsalvar" value="Salvar" /> 
                <a onClick="history.go(-1)" class="btn btn-default">Cancelar</a>
        </div>

    <?php echo form_close(); ?>
</body>
</html>