<!DOCTYPE html>
<html lang="pt-BR">

<head>

	<meta charset="utf-8">

  <script type="text/javascript">  
    $(function(){
        $("#nomeEvento").autocomplete({
          source: "clientes/get_cliente", // path to the method
          appendTo: $("#new_event")
        });
    }); 
  </script>

  <script>
  $(function(){
      $('.form-control.date').datepicker({
          format: 'yyyy-mm-dd',
          language: 'pt-BR',
          todayHighlight: true
      });
   });
  </script>
	
</head>

<body>

	<div class="row" >
		<form action="/sistema/representantes/pesquisar" method="post">
			<div class="col-sm-9">
				<div class="form-group">
					<input name="search" class="form-control" id="search" type="text"
						placeholder="Filtrar Representante " value="<?php echo $view_termo??null ;?>">  
						<span class="input-group-btn"></span>
				</div>
			</div>

			<div class="col-sm-1">
				<button class="btn btn-primary pull-left btn-sm" type="submit">Filtrar</button>
			</div>

		</form>

		<div class="col-sm-2">
			<a data-toggle="modal" data-target="#new_representante" class="btn btn-primary btn-sm ">Adicionar Rep</a>
		</div>

	</div>

	<div id="list" class="row">
		<div class="table-responsive col-md-12">
			<table class="table table-striped" cellspacing="0" cellpadding="0" id="representantes">
				<thead>
					<tr>
						<th>ID</th>
						<th>Nome</th>
						<th>Email</th>
						<th>Fone</th>
						<th class="actions">Ações</th>
					</tr>
				</thead>
				
				<tbody>

					<?php foreach ( $representantes as $representante ) {?>
						<tr>
							<td><?php echo $representante->rcod; ?></td>    
							<td><?php echo $representante->rnome; ?></td>    
							<td><?php echo $representante->email; ?></td>
							<td><?php echo $representante->fone; ?></td>
							<td class="actions">
								<a title="Editar" class="btn btn-warning btn-sm fa fa-pencil-square-o" href="<?php echo base_url() . 'representantes/editar/' . $representante->rcod; ?>"></a>
								<a title="Deletar" class="btn btn-danger btn-sm fa fa-trash" href="<?php echo base_url() . 'representantes/deletar/' . $representante->rcod; ?>" onclick="return confirm('Confirma a exclusão deste registro?')"></a>
							</td>		

						</tr>	 	 	  	
						  	
				 	<?php } ?>
				</tbody>
			</table>
				<h4><?php echo $this->session->flashdata('mensagem');?></h4>
				<h4><?php echo $this->session->flashdata('mensagemErro');?></h4>
		</div>
	</div>	
	
	<div class="row">
      <div class="col-sm-10" >
        <?php echo $pagination; ?>
      </div>
      <div class="col-sm-2" >
        <a class="btn btn-primary btn-sm" download="somedata.xls" href="#" 
        onclick="return ExcellentExport.excel(this, 'representantes', 'relatorio');">Export to Excel</a>
      </div>

    </div>

</body>



<!-- Modal de inserir-->
<div class="modal fade" id="new_representante" tabindex="-1" role="dialog" aria-labelledby="modalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header  bg-red"">
        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modalLabel">Adicionar representante</h4>
      </div>
      <div class="modal-body">
       
   <?php echo form_open('representantes/inserir', 'id="form-representantes"'); ?>
    
    <form action="" method="post" ENCTYPE="multipart/form-data">
      <div class="row">
        <div class="form-group col-md-5">
            <label for="rnome">Nome do Representante</label> 
            <input type="text" class="form-control" id="rnome" name="rnome"
                placeholder="informe o nome do representante" required
                value="<?php echo isset($view_rnome) ? $view_rnome: '' ; ?>">
        </div>     
        <div class="form-group col-md-5">
            <label for="email">email</label> 
            <input type="email" class="form-control" id="email" name="email"
                placeholder="informe o email do representantes" required
                value="<?php echo isset($view_email) ? $view_email: '' ; ?>">
        </div>
    </div>

    <div class="row">
        <div class="form-group col-md-5">
            <label for="fone">Fone</label> 
            <input type="text" class="form-control" id="fone" name="fone"
                placeholder="informe o telefone do representante" required
                value="<?php echo isset($view_fone) ? $view_fone: '' ; ?>">
        </div>     
    </div>
    
        <div class="row">
        <div class="col-md-12">
            <input href="http://localhost/sistema/representantes/inserir"  type="submit" class="btn btn-primary" name="btsalvar" value="Salvar" /> 
                <a data-dismiss="modal" class="btn btn-default">Cancelar</a>
        </div>

    <?php echo form_close(); ?>

		</div>

      </div>
    </div>
  </div>
</div> <!-- /.modal -->


<!-- Modal de inserir evento -->
<div class="modal fade" id="new_event" tabindex="-1" role="dialog" aria-labelledby="modalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header  bg-red"">
        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modalLabel">Adicionar evento</h4>
      </div>
      <div class="modal-body">
       
       <?php echo form_open('calendar2/new_event', 'id="form-events"'); ?>
        
        <form action="" method="post" ENCTYPE="multipart/form-data">
          <div class="row">
            <div class="form-group col-md-6">
                <label for="nomeEvento">Nome Cliente</label> 
                <input type="text" class="form-control" id="nomeEvento" name="nomeEvento" placeholder="informe o nome do cliente" required
                value="<?php echo isset($view_enome) ? $view_enome: '' ; ?>">
            </div>  

            <div class="form-group col-md-6">
              <label for="user">Responsavel</label> 
              <input type="text" class="form-control" id="user" 
              name="user" readonly value="<?php echo $_SESSION['usuario_logado']['username']; ?> "/>
            </div>
          </div> 

          <div class="row"> 
            <div class="col-md-6">
              <label for="inicio">Data</label>
            </div>
            <div class="col-md-6">
              <label for="importancia">Prioridade</label>
            </div>
            <div class="form-group col-md-6">
              <div class="input-group date">
                <input type="text" class="form-control date" id="inicio" name="inicio" required
                 placeholder="Data de inicio" value="<?php echo isset($view_inicio) ? $view_inicio: '' ; ?>">
                <div class="input-group-addon"> 
                  <span class="glyphicon glyphicon-th"></span>
                </div>
              </div>
            </div>

            <div class="form-group col-md-6">
              <div class="col-md-2">
                <input type="radio" name="importancia" value="Alta" checked> Alta<br>
              </div>
              <div class="col-md-2">
                <input type="radio" name="importancia" value="Media"> Media<br>
              </div>
              <div class="col-md-2">
                <input type="radio" name="importancia" value="Baixa"> Baixa<br>
              </div>
            </div>


          </div>

           <div class="row"> 
            <div class="form-group col-md-12">
              <label for="descricaoEvento">Descrição</label> 
              <input type="text" class="form-control" id="descricaoEvento" name="descricaoEvento" placeholder="descreva a tarefa" required
                value="<?php echo isset($view_descricaoEvento) ? $view_descricaoEvento: '' ; ?>">
            </div> 
           </div>


          <div class="row">
            <div class="col-md-12">
                <input href="http://localhost/sistema/calendar2/new_event"  type="submit" class="btn btn-primary" name="btsalvar" value="Salvar" /> 
                    <a data-dismiss="modal" class="btn btn-default">Cancelar</a>
            </div>

        <?php echo form_close(); ?>
        </div>    
        </form>
		  </div>

      </div>
    </div>
  </div><!-- /.modal -->


</html>