<!DOCTYPE html>
<html lang="pt-BR">

<head>

	<meta charset="utf-8">
	
</head>

<body>

	<div class="row" >
		<form action="/sistema/representantes/pesquisar" method="post">
			<div class="col-sm-9">
				<div class="form-group">
					<input name="search" class="form-control" id="search" type="text"
						placeholder="Filtrar Representante " value="<?php echo $view_termo??null ;?>">  
						<span class="input-group-btn"></span>
				</div>
			</div>

			<div class="col-sm-1">
				<button class="btn btn-primary pull-left" type="submit">Filtrar</button>
			</div>

		</form>

		<div class="col-sm-2">
			<a data-toggle="modal" data-target="#new_representante" class="btn btn-primary ">Adicionar Rep</a>
		</div>

	</div>

	<div id="list" class="row">
		<div class="table-responsive col-md-12">
			<table class="table table-striped" cellspacing="0" cellpadding="0" id="representantes">
				<thead>
					<tr>
						<th>ID</th>
						<th>Nome</th>
						<th>Email</th>
						<th>Fone</th>
						<th class="actions">Ações</th>
					</tr>
				</thead>
				
				<tbody>

					<?php foreach ( $representantes as $representante ) {?>
						<tr>
							<td><?php echo $representante->rcod; ?></td>    
							<td><?php echo $representante->rnome; ?></td>    
							<td><?php echo $representante->email; ?></td>
							<td><?php echo $representante->fone; ?></td>
							<td class="actions">
								<a title="Editar" class="btn btn-warning btn-sm fa fa-pencil-square-o" href="<?php echo base_url() . 'representantes/editar/' . $representante->rcod; ?>"></a>
								<a title="Deletar" class="btn btn-danger btn-sm fa fa-trash" href="<?php echo base_url() . 'representantes/deletar/' . $representante->rcod; ?>" onclick="return confirm('Confirma a exclusão deste registro?')"></a>
							</td>		

						</tr>	 	 	  	
						  	
				 	<?php } ?>
				</tbody>
			</table>
				<h3><?php echo $this->session->flashdata('mensagem');?></h3>
				<h3><?php echo $this->session->flashdata('mensagemErro');?></h3>
		</div>
	</div>	
	
	<div class="row">
      <div class="col-sm-10" >
        <?php echo $pagination; ?>
      </div>
      <div class="col-sm-2" >
        <a class="btn btn-primary btn-sm" download="somedata.xls" href="#" 
        onclick="return ExcellentExport.excel(this, 'representantes', 'relatorio');">Export to Excel</a>
      </div>

    </div>

</body>



<!-- Modal de inserir-->
<div class="modal fade" id="new_representante" tabindex="-1" role="dialog" aria-labelledby="modalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header  bg-red"">
        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modalLabel">Adicionar representante</h4>
      </div>
      <div class="modal-body">
       
   <?php echo form_open('representantes/inserir', 'id="form-representantes"'); ?>
    
    <form action="" method="post" ENCTYPE="multipart/form-data">
      <div class="row">
        <div class="form-group col-md-5">
            <label for="rnome">Nome do Representante</label> <input type="text" class="form-control" id="rnome" name="rnome"
                placeholder="informe o nome do representante"
                value="<?php echo isset($view_rnome) ? $view_rnome: '' ; ?>">
        </div>     
        <div class="form-group col-md-5">
            <label for="email">email</label> <input type="text" class="form-control" id="email" name="email"
                placeholder="informe o email do representantes"
                value="<?php echo isset($view_email) ? $view_email: '' ; ?>">
        </div>
    </div>

    <div class="row">
        <div class="form-group col-md-5">
            <label for="fone">Fone</label> <input type="text" class="form-control" id="fone" name="fone"
                placeholder="informe o telefone do representante"
                value="<?php echo isset($view_fone) ? $view_fone: '' ; ?>">
        </div>     
    </div>
    
        <div class="row">
        <div class="col-md-12">
            <input href="http://localhost/sistema/representantes/inserir"  type="submit" class="btn btn-primary" name="btsalvar" value="Salvar" /> 
                <a data-dismiss="modal" class="btn btn-default">Cancelar</a>
        </div>

    <?php echo form_close(); ?>

		</div>

      </div>
    </div>
  </div>
</div> <!-- /.modal -->


</html>