<!DOCTYPE html>
<html>
 	<head>
	    <div class="row">
		    <div class="col-md-12">
				<select class="selectpicker" id="charts">
				  <option>Produtos orçados</option>
				  <option>Situações orçadas</option>
				  <option>Numeros da equipe</option>
				</select>		
		          <!--<input type="submit" class="btn btn-primary" name="btsalvar" value="Salvar" />-->
		    </div>
		</div>
	</head>

	<body>
	
		

	</body>

</html>
